
##Standard packages for all CCISS_2019 scripts
require (RGtk2)
require(plyr)
# require (rChoiceDialogs)
require (data.table)
require(doBy)
require (utils)
require(labdsv)
require(tools )
require(svDialogs)
require(tcltk)
require(randomForest)
require(ranger)
require(foreach)
require(dplyr)
require(reshape2)
require(reshape)
require(doParallel)
require(data.table)
require(MASS)   
require(scales)
require(stats)
require(rgl)
require(RColorBrewer)
require(FNN)
require(igraph)
require(raster)
require(maps)
require(mapdata)
require(maptools)
require(sp)
require(colorRamps)
require(rgeos)
require(rgdal)
require(foreign)
library(iterators)